### ISSUE TITLE
Having trouble getting started

### ISSUE THREAD

**Issue by spacecowboyian** [punkave/apostrophe-people#12]
is there a good guide for how to get going with people/groups?

I have:
- Added a page type of directory
- Made a directory page
- Had to move templates from the modules into my views folder to make the directory show
- It seems to have no data even though there are 3 users added

![screen shot 2016-06-20 at 3 49 38 pm](https://cloud.githubusercontent.com/assets/77822/16209861/9ea5cc7c-36fe-11e6-9c40-a13e86696524.png)

**Comment by boutell** [comment]
Are your users in a group?

If you just want to list people and groups are not really on your radar,
consider using the "simplePages: true" option to apostrophe-people, in
which case you can just create index and show templates for the people
module and keep groups out of it.

For 0.6 we decided this setup was more trouble than it was worth. For most
projects we are creating separate pieces (subclasses of snippets, in 0.5
terms) to represent people, departments, etc. in a directory and not
confusing that with the concepts of users and groups as they relate to
logins and permissions at all. You can do that in 0.5 too.

On Mon, Jun 20, 2016 at 4:50 PM, Ian Jennings <notifications@github.com>
wrote:

> is there a good guide for how to get going with people/groups?
>
> I have:
>
>    - Added a page type of directory
>    - Made a directory page
>    - Had to move templates from the modules into my views folder to make
>    the directory show
>    - It seems to have no data even though there are 3 users added
>
> [image: screen shot 2016-06-20 at 3 49 38 pm]
> <https://cloud.githubusercontent.com/assets/77822/16209861/9ea5cc7c-36fe-11e6-9c40-a13e86696524.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe-people/issues/12>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAB9fVVPdlAS52fCdhFsPLAUENiavzo8ks5qNvz8gaJpZM4I6HEW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by spacecowboyian** [comment]
They are in a group. My final result will be to list the people in the group on the home page of the site anyway. I was just trying to get the directory page to work as a first step. Any advice for getting at the data to display a group on the home page?

**Comment by boutell** [comment]
The groups widget was never terribly well-baked. As I mentioned you're
probably better off creating new content types for staff and departments,
independent of the login-related people and groups modules.

But you can add the "groups" widget to an area, and override widget.html
for the groups module to iterate over group._people for each group selected
in the widget.


On Tue, Jun 21, 2016 at 2:56 PM, Ian Jennings <notifications@github.com>
wrote:

> They are in a group. My final result will be to list the people in the
> group on the home page of the site anyway. I was just trying to get the
> directory page to work as a first step. Any advice for getting at the data
> to display a group on the home page?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe-people/issues/12#issuecomment-227537429>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fQGZSvppe-9SuTre_DYTnOnlG793ks5qODP5gaJpZM4I6HEW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by spacecowboyian** [comment]
ahhhh.. groups widget.. I'll try that route then back off to the custom content types if needed.

Thanks Tom!

**Comment by spacecowboyian** [comment]
I tagged the group and every person with the same tag. Then I logged group in my new widget.html template. group is coming back as undefined.

**Comment by boutell** [comment]
This isn't how people are added to groups. You edit the group and there's a
place to autocomplete people's names and add them to a direct relationship
with the group.


On Tue, Jun 21, 2016 at 3:54 PM, Ian Jennings <notifications@github.com>
wrote:

> I tagged the group and every person with the same tag. Then I logged group
> in my new widget.html template. group is coming back as undefined.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe-people/issues/12#issuecomment-227552617>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fS4-RlY4eUvdKiYYcSMuacP3AS8iks5qOEF9gaJpZM4I6HEW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by spacecowboyian** [comment]
I had already done that. I think the groups widget interface is way broken for me:

![screen shot 2016-06-21 at 3 32 43 pm](https://cloud.githubusercontent.com/assets/77822/16245226/795dc6c8-37c5-11e6-8cf9-e6fef71bc60f.png)

**Comment by spacecowboyian** [comment]
Anyway I've tagged the group with UX trying to pull it in. I can't use the "by name" option because I can't scroll down to that point.

**Comment by boutell** [comment]
That's pretty broken all right. I am not sure we are actually using this
particular widget at this point but I'm a little surprised that you can't
scroll in it.

On Tue, Jun 21, 2016 at 4:34 PM, Ian Jennings <notifications@github.com>
wrote:

> Anyway I've tagged the group with UX trying to pull it in. I can't use the
> "by name" option because I can't scroll down to that point.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe-people/issues/12#issuecomment-227563060>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fah3SBZimB2f4KFEc5U9niz2qI6vks5qOErAgaJpZM4I6HEW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by spacecowboyian** [comment]
There's nothing in it after that radio button.

`<fieldset class="apos-fieldset apos-fieldset-radio">
  <label>{{ __('By Name') }}</label>
  <input type="radio" name="by" value="id" />
</fieldset>

{% endblock %}`

I'd expect there to be a text input after that but there isn't one in the template:

https://github.com/punkave/apostrophe-groups/blob/master/views/widgetEditor.html

**Comment by boutell** [comment]
Safe to say we're not using this widget.

What I would recommend is that if you want to share people in this way, you
set simplePages: true for the people module. Then you can just use the
people widget (rather than the groups widget) and add index pages for
people (rather than groups), and filter them down by tags, same as you
would most snippet types. This is a model we actually do use sometimes (:

On Tue, Jun 21, 2016 at 4:48 PM, Ian Jennings <notifications@github.com>
wrote:

> There's nothing in it after that radio button.
>
> `
>
> {{ __('By Name') }}
>
> {% endblock %}`
>
> I'd expect there to be a text input after that but there isn't one in the
> template:
>
>
> https://github.com/punkave/apostrophe-groups/blob/master/views/widgetEditor.html
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe-people/issues/12#issuecomment-227566936>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fU0D7cBAuOj-l8_q96z8zb3GLc2Xks5qOE4AgaJpZM4I6HEW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by spacecowboyian** [comment]
I actually used schema-widgets and created a group widget using a join to groups. Picked the group with the widget then just looped over the people in the group.

**Comment by boutell** [comment]
That's a fine solution too!


On Wed, Jun 22, 2016 at 7:43 PM, Ian Jennings <notifications@github.com>
wrote:

> I actually used schema-widgets and created a group widget using a join to
> groups. Picked the group with the widget then just looped over the people
> in the group.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe-people/issues/12#issuecomment-227909854>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fQVSdooR9Q1DtJr3P5OiI3NnVTKkks5qOciHgaJpZM4I6HEW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com
